
import { FileInput, RubricCriterion, BriefAdherence } from '../types';
import mammoth from 'mammoth';

export const readFileAsBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      const base64 = result.split(',')[1];
      resolve(base64);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

export const readFileAsText = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsText(file);
  });
};

export const readDocxAsText = async (file: File): Promise<string> => {
  try {
    const arrayBuffer = await file.arrayBuffer();
    const result = await mammoth.extractRawText({ arrayBuffer });
    return result.value;
  } catch (error) {
    console.error("Failed to parse DOCX:", error);
    return `[Error parsing DOCX file]`;
  }
};

export const determineFileType = (file: File): FileInput['type'] => {
  if (file.type === 'application/pdf' || file.name.toLowerCase().endsWith('.pdf')) return 'pdf';
  if (file.type.startsWith('image/') || /\.(jpg|jpeg|png|webp)$/i.test(file.name)) return 'image';
  if (file.name.toLowerCase().endsWith('.docx')) return 'docx';
  return 'text';
};

export const generateReportText = (result: any): string => {
  const briefText = result.briefAdherence.map((task: BriefAdherence) => {
    return `
TASK: ${task.taskName} [ADHERENCE: ${task.adherenceLevel}]
- EVIDENCE: "${task.evidence}"
- COMMENTARY: ${task.commentary}
    `.trim();
  }).join('\n\n');

  const rubricText = result.rubricAlignment.map((crit: RubricCriterion) => {
    return `
CRITERION: ${crit.criterion} [SCORE: ${crit.score}]
- EVIDENCE FOUND: "${crit.evidenceFound}"
- MISSING ELEMENTS: ${crit.missingEvidence}
- REASONING: ${crit.criticalReasoning}
    `.trim();
  }).join('\n\n');

  return `
ACADEMIC ASSESSMENT AUDIT REPORT
================================
Student: ${result.studentName}
File: ${result.fileName}
Date: ${result.timestamp}

FINAL MARK: ${result.mark}
GRADE BAND: ${result.grade}

--- QUANTITATIVE ANALYSIS ---
TECHNICAL DENSITY:
${result.technicalDensity}

WEIGHT OF WORK ANALYSIS:
${result.wordCountAnalysis}

--- EXECUTIVE SUMMARY ---
STRENGTHS (WWW):
${result.www}

CRITICAL GAPS (EBI):
${result.ebi}

STRATEGIC FEED FORWARD:
${result.feedForward}

--- BRIEF ADHERENCE AUDIT ---
${briefText}

--- DETAILED RUBRIC AUDIT ---
${rubricText}

--------------------------
Generated by The Academic Assessment AI
Deterministic Evidence Protocol v3.0
  `.trim();
};
